// We don't test the greatest range that does not fail, to keep the tests fast.
let still_ok = std.range(0, 100);
let err = std.range(10, 1_000_011);
0

# output:
stdin:3:34
  ╷
3 │ let err = std.range(10, 1_000_011);
  ╵                                  ^
Error: Range 10..1000011 exceeds the maximum length of 1000000. The list would require too much memory.

stdin:3:20
  ╷
3 │ let err = std.range(10, 1_000_011);
  ╵                    ^
In call to function 'std.range'.
